<html>
<head>
<title>RecoverableErrorTest.cpp</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #808080;}
.s1 { color: #a9b7c6;}
.s2 { color: #bbb529;}
.s3 { color: #6a8759;}
.s4 { color: #cc7832;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
RecoverableErrorTest.cpp</font>
</center></td></tr></table>
<pre><span class="s0">/* 
 * Copyright (c) Meta Platforms, Inc. and affiliates. 
 * 
 * This source code is licensed under the MIT license found in the 
 * LICENSE file in the root directory of this source tree. 
 */</span>

<span class="s2">#include </span><span class="s3">&lt;gtest/gtest.h&gt;</span>

<span class="s2">#include </span><span class="s3">&lt;exception&gt;</span>
<span class="s2">#include </span><span class="s3">&lt;stdexcept&gt;</span>

<span class="s2">#include </span><span class="s3">&lt;cxxreact/RecoverableError.h&gt;</span>

<span class="s4">using namespace </span><span class="s1">facebook::react</span><span class="s4">;</span>

<span class="s1">TEST(RecoverableError</span><span class="s4">, </span><span class="s1">RunRethrowingAsRecoverableRecoverTest) {</span>
  <span class="s4">try </span><span class="s1">{</span>
    <span class="s1">RecoverableError::runRethrowingAsRecoverable&lt;std::runtime_error&gt;(</span>
        <span class="s1">[]() { </span><span class="s4">throw </span><span class="s1">std::runtime_error(</span><span class="s3">&quot;catch me&quot;</span><span class="s1">)</span><span class="s4">; </span><span class="s1">})</span><span class="s4">;</span>
    <span class="s1">FAIL() &lt;&lt; </span><span class="s3">&quot;Unthrown exception&quot;</span><span class="s4">;</span>
  <span class="s1">} </span><span class="s4">catch </span><span class="s1">(</span><span class="s4">const </span><span class="s1">RecoverableError &amp;err) {</span>
    <span class="s1">ASSERT_STREQ(err.what()</span><span class="s4">, </span><span class="s3">&quot;facebook::react::Recoverable: catch me&quot;</span><span class="s1">)</span><span class="s4">;</span>
  <span class="s1">} </span><span class="s4">catch </span><span class="s1">(...) {</span>
    <span class="s1">FAIL() &lt;&lt; </span><span class="s3">&quot;Uncaught exception&quot;</span><span class="s4">;</span>
  <span class="s1">}</span>
<span class="s1">}</span>

<span class="s1">TEST(RecoverableError</span><span class="s4">, </span><span class="s1">RunRethrowingAsRecoverableFallthroughTest) {</span>
  <span class="s4">try </span><span class="s1">{</span>
    <span class="s1">RecoverableError::runRethrowingAsRecoverable&lt;std::runtime_error&gt;(</span>
        <span class="s1">[]() { </span><span class="s4">throw </span><span class="s1">std::logic_error(</span><span class="s3">&quot;catch me&quot;</span><span class="s1">)</span><span class="s4">; </span><span class="s1">})</span><span class="s4">;</span>
    <span class="s1">FAIL() &lt;&lt; </span><span class="s3">&quot;Unthrown exception&quot;</span><span class="s4">;</span>
  <span class="s1">} </span><span class="s4">catch </span><span class="s1">(</span><span class="s4">const </span><span class="s1">RecoverableError &amp;err) {</span>
    <span class="s1">FAIL() &lt;&lt; </span><span class="s3">&quot;Recovered exception that should have fallen through&quot;</span><span class="s4">;</span>
  <span class="s1">} </span><span class="s4">catch </span><span class="s1">(</span><span class="s4">const </span><span class="s1">std::exception &amp;err) {</span>
    <span class="s1">ASSERT_STREQ(err.what()</span><span class="s4">, </span><span class="s3">&quot;catch me&quot;</span><span class="s1">)</span><span class="s4">;</span>
  <span class="s1">}</span>
<span class="s1">}</span>
</pre>
</body>
</html>